version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - CONFIG_PATH=/config/config.yaml
      - STORAGE=postgres
      - POSTGRES_DSN=postgres://shortener:secret@db:5432/shortener?sslmode=disable
    ports:
      - "8080:8080"
      - "50051:50051"

volumes:
  db_data:
