// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: urlshortner.proto

package urlshortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenUrlRequest) Reset() {
	*x = ShortenUrlRequest{}
	mi := &file_urlshortner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenUrlRequest) ProtoMessage() {}

func (x *ShortenUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenUrlRequest.ProtoReflect.Descriptor instead.
func (*ShortenUrlRequest) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenUrlResponse) Reset() {
	*x = ShortenUrlResponse{}
	mi := &file_urlshortner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenUrlResponse) ProtoMessage() {}

func (x *ShortenUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenUrlResponse.ProtoReflect.Descriptor instead.
func (*ShortenUrlResponse) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenUrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortenUrlResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetOriginalUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortKey      string                 `protobuf:"bytes,1,opt,name=short_key,json=shortKey,proto3" json:"short_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalUrlRequest) Reset() {
	*x = GetOriginalUrlRequest{}
	mi := &file_urlshortner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalUrlRequest) ProtoMessage() {}

func (x *GetOriginalUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalUrlRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalUrlRequest) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalUrlRequest) GetShortKey() string {
	if x != nil {
		return x.ShortKey
	}
	return ""
}

type GetOriginalUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalUrlResponse) Reset() {
	*x = GetOriginalUrlResponse{}
	mi := &file_urlshortner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalUrlResponse) ProtoMessage() {}

func (x *GetOriginalUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalUrlResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalUrlResponse) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalUrlResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_urlshortner_proto protoreflect.FileDescriptor

const file_urlshortner_proto_rawDesc = "" +
	"\n" +
	"\x11urlshortner.proto\x12\x0furlshortener.v1\"%\n" +
	"\x11ShortenUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"T\n" +
	"\x12ShortenUrlResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"4\n" +
	"\x15GetOriginalUrlRequest\x12\x1b\n" +
	"\tshort_key\x18\x01 \x01(\tR\bshortKey\";\n" +
	"\x16GetOriginalUrlResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl2\xd3\x01\n" +
	"\x13UrlShortenerService\x12W\n" +
	"\n" +
	"ShortenUrl\x12\".urlshortener.v1.ShortenUrlRequest\x1a#.urlshortener.v1.ShortenUrlResponse\"\x00\x12c\n" +
	"\x0eGetOriginalUrl\x12&.urlshortener.v1.GetOriginalUrlRequest\x1a'.urlshortener.v1.GetOriginalUrlResponse\"\x00BJZHgithub.com/socialrating/urlshortener/api/proto/urlshortener;urlshortenerb\x06proto3"

var (
	file_urlshortner_proto_rawDescOnce sync.Once
	file_urlshortner_proto_rawDescData []byte
)

func file_urlshortner_proto_rawDescGZIP() []byte {
	file_urlshortner_proto_rawDescOnce.Do(func() {
		file_urlshortner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urlshortner_proto_rawDesc), len(file_urlshortner_proto_rawDesc)))
	})
	return file_urlshortner_proto_rawDescData
}

var file_urlshortner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_urlshortner_proto_goTypes = []any{
	(*ShortenUrlRequest)(nil),      // 0: urlshortener.v1.ShortenUrlRequest
	(*ShortenUrlResponse)(nil),     // 1: urlshortener.v1.ShortenUrlResponse
	(*GetOriginalUrlRequest)(nil),  // 2: urlshortener.v1.GetOriginalUrlRequest
	(*GetOriginalUrlResponse)(nil), // 3: urlshortener.v1.GetOriginalUrlResponse
}
var file_urlshortner_proto_depIdxs = []int32{
	0, // 0: urlshortener.v1.UrlShortenerService.ShortenUrl:input_type -> urlshortener.v1.ShortenUrlRequest
	2, // 1: urlshortener.v1.UrlShortenerService.GetOriginalUrl:input_type -> urlshortener.v1.GetOriginalUrlRequest
	1, // 2: urlshortener.v1.UrlShortenerService.ShortenUrl:output_type -> urlshortener.v1.ShortenUrlResponse
	3, // 3: urlshortener.v1.UrlShortenerService.GetOriginalUrl:output_type -> urlshortener.v1.GetOriginalUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_urlshortner_proto_init() }
func file_urlshortner_proto_init() {
	if File_urlshortner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urlshortner_proto_rawDesc), len(file_urlshortner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urlshortner_proto_goTypes,
		DependencyIndexes: file_urlshortner_proto_depIdxs,
		MessageInfos:      file_urlshortner_proto_msgTypes,
	}.Build()
	File_urlshortner_proto = out.File
	file_urlshortner_proto_goTypes = nil
	file_urlshortner_proto_depIdxs = nil
}
