openapi: 3.1.0
info:
  title: URL Shortener API
  version: 1.0.0
paths:
  /url:
    post:
      summary: Create a short URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  example: "https://example.com/very/long/url/to/shorten"
              required:
                - url
      responses:
        '200':
          description: Short URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    example: "aB_1cD2eF3"
  /{short_url}:
    get:
      summary: Get original URL
      parameters:
        - name: short_url
          in: path
          required: true
          schema:
            type: string
            example: "aB_1cD2eF3"
      responses:
        '307':
          description: Temporary Redirect to the original URL.
        '404':
          description: Short URL not found.